# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='type',
            new_name='ssh_name',
        ),
        migrations.AddField(
            model_name='port',
            name='ssh_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
